### ISSUE TITLE
Reto semana 2

### ISSUE THREAD

**Issue by andresmgsl** [jMontedeoca/HeavyDutyCamp#2]
Holaa, espero estés bien.. Hemos aprobado tu Reto de semana 2, pero nos gustaría pedirte que para los retos 3 y 4 usaras Branchs y pull request, mas o menos como lo que hiciste en el Reto 1 

De igual forma está aprobado, y te agradecemos estar participando! 😁

**Comment by jMontedeoca** [comment]
Gracias por el feedback!
para el reto 2 bonus no lo hice, pero ya lo hago para el reto 3 😊

**Comment by andresmgsl** [comment]
Nada, gracias a ti por participar con nosotros :grin: ... Cualquier duda estamos a la orden!
